config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  resources :rss_items do
    collection do
      get 'reset_filters'
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'rss_items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/feed.rb
# app/models/feed.rb
class Feed < ApplicationRecord
  has_many :rss_items, dependent: :destroy
  validates :url, presence: true
  validates :url, uniqueness: true
  validate :valid_url

  def valid_url
    return if url.blank? || url =~ URI::DEFAULT_PARSER.make_regexp

    errors.add(:url, 'is not a valid URL')
  end
end

app/models/rss_item.rb
# app/models/rss_item.rb
class RssItem < ApplicationRecord
  belongs_to :feed
  validates :feed_id, presence: true
  validates :link, uniqueness: { scope: %i[feed_id publish_date] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feeds_controller.rb
# app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: %i[show edit update destroy]

  # GET /feeds
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  def show; end

  # GET /feeds/new
  def new
    @feed = Feed.new
    @feeds_with_errors = []
  end

  # GET /feeds/1/edit
  def edit; end

  # POST /feeds
  def create
    urls = feed_params[:urls].split(/[,;\s\n\t\r\f\v]+/).map(&:strip).reject(&:empty?)

    if urls.empty?
      handle_empty_urls
    else
      @feeds_with_errors = create_feeds_with_errors(urls)
      handle_create_result
    end
  end

  # PATCH/PUT /feeds/1
  def update
    if @feed.update(feed_params)
      redirect_to @feed, notice: 'Feed was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /feeds/1
  def destroy
    @feed.destroy!
    redirect_to feeds_url, notice: 'Feed was successfully destroyed.', status: :see_other
  end

  private

  def handle_empty_urls
    flash.now[:alert] = 'No URLs provided. Please enter at least one URL.'
    @feed = Feed.new
    @feeds_with_errors = []
    render :new, status: :unprocessable_entity
  end

  def handle_create_result
    if @feeds_with_errors.empty?
      redirect_to feeds_path, notice: 'Feeds were successfully created.'
    else
      @feed = Feed.new
      render :new, status: :unprocessable_entity
    end
  end

  def create_feeds_with_errors(urls)
    feeds_with_errors = []

    urls.each do |url|
      feed = Feed.new(url:)
      feeds_with_errors << feed unless feed.save
    end

    feeds_with_errors
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_feed
    @feed = Feed.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def feed_params
    params.require(:feed).permit(:urls, :url)
  end
end

app/controllers/rss_items_controller.rb
# app/controllers/rss_items_controller.rb
class RssItemsController < ApplicationController
  before_action :set_rss_item, only: %i[show destroy]

  def index
    @rss_items = filter_and_paginate_rss_items
  end

  def show; end

  def destroy
    @rss_item.destroy!
    redirect_to rss_items_url, notice: 'Archive item was successfully destroyed.', status: :see_other
  end

  def reset_filters
    redirect_to rss_items_path
  end

  private

  def filter_and_paginate_rss_items
    rss_items = RssItem.order('publish_date DESC')
    rss_items = apply_source_filter(rss_items)
    rss_items = apply_title_filter(rss_items)
    rss_items = apply_publish_date_filter(rss_items)
    rss_items.paginate(page: params[:page], per_page: 25)
  end

  def apply_source_filter(rss_items)
    return rss_items unless params[:source].present?

    rss_items.where('source LIKE ?', "%#{params[:source]}%")
  end

  def apply_title_filter(rss_items)
    return rss_items unless params[:title].present?

    rss_items.where('title LIKE ?', "%#{params[:title]}%")
  end

  def apply_publish_date_filter(rss_items)
    return rss_items unless params[:publish_date].present?

    date = Date.parse(params[:publish_date])
    rss_items.where('publish_date >= ? AND publish_date < ?', date, date + 1.day)
    # @rss_items = @rss_items.where("publish_date >= date(?) AND publish_date < date(?, '+1 day')",
    #                           params[:publish_date], params[:publish_date])
  end

  def set_rss_item
    @rss_item = RssItem.find(params[:id])
  end
end

app/views/feeds/_feed.html.slim
div id="#{dom_id feed}"
  p
    strong Url:
    =< feed.url

app/views/feeds/_form.html.slim
= form_with(model: feed, local: true, html: { class: 'form' }) do |form|
  - if feed.errors.any?
    .alert.alert-danger
      h2 = "#{pluralize(feed.errors.count, 'error')} prohibited this feed from being saved:"
      ul
        - feed.errors.each do |error|
          li = error.full_message

  .form-group
    = form.label :url, class: 'control-label'
    = form.text_field :url, class: 'form-control'
    br
  .form-group
    = form.submit 'Save', class: 'btn btn-success'

app/views/feeds/_new_form.html.slim
= form_with(model: @feed, local: true, html: { class: 'form' }) do |form|
  - if @feeds_with_errors.any?
    .alert.alert-danger
      h4 = "The following errors prevented some feeds from being saved:"
      ul
        - @feeds_with_errors.each do |feed|
          - if feed.errors.any?
            li
              h5 #{feed.url}
              ul
                - feed.errors.full_messages.each do |error|
                  li = error

  .form-group
    = form.label :urls
    = form.text_area :urls, rows: 10, class: 'form-control'
    small.text-muted
      |
        insert multiple URLs, separated by spaces, commas or new lines.

  .form-group
    = form.submit 'Save', class: 'btn btn-success'

app/views/feeds/edit.html.slim
div.container
  h1 Editing Feed

  == render "form", feed: @feed

  br

  div.btn-toolbar.mt-3
    = link_to "Show this feed", @feed, class: "btn btn-primary mr-2"
    |
    = link_to "Back to feeds", feeds_path, class: "btn btn-secondary"

app/views/feeds/index.html.slim
p style="color: green" = notice

.row
  .col-md-8
    h1 Feeds
  .col-md-4.text-right
    = link_to "New feed", new_feed_path, class: "btn btn-success"

table.table.table-bordered
  thead
    tr
      th URL
      th Actions
  tbody#feeds
    - @feeds.each do |feed|
      tr
        td == feed.url
        td.d-flex.justify-content-start.gap-3
          = link_to "Show", feed, class: "btn btn-primary btn-sm"
          = link_to "Edit", edit_feed_path(feed), class: "btn btn-secondary btn-sm" 
          = button_to "Delete", feed, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" 

app/views/feeds/new.html.slim
div.container
  h1 New feed

  == render "new_form", feed: @feed

  br

  div
    = link_to "Back to feeds", feeds_path, class: "btn btn-primary"

app/views/feeds/show.html.slim
div.container
  p style="color: green" = notice

  == render @feed

  div.d-flex.justify-content-start.gap-3
    = link_to "Edit this feed", edit_feed_path(@feed), class: "btn btn-secondary"
    
    = link_to "Back to feeds", feeds_path, class: "btn btn-primary"

    = button_to "Destroy this feed", @feed, method: :delete, class: "btn btn-danger"

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  a.navbar-brand RSS reader

  #navbarNav
    ul.navbar-nav
      li.nav-item
        = link_to "Feeds", feeds_path, class: "nav-link"

      li.nav-item
        = link_to "Archive", rss_items_path, class: "nav-link"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rssfront</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/rss_items/_rss_item.html.slim
div id="#{dom_id rss_item}"
  p
    strong Title:
    =< rss_item.title
  p
    strong Source:
    =< rss_item.source
  p
    strong Source url:
    =< rss_item.source_url
  p
    strong Link:
    =< rss_item.link
  p
    strong Description:
    =< rss_item.description
  p
    strong Publish date:
    =< rss_item.publish_date

app/views/rss_items/index.html.slim
.row
  .col-md-9
    - @rss_items.each do |item|
      div.row
        div.col-md-8
          a href=item['link'] target='_blank' = item['title']
        div.col-md-4.d-flex.justify-content-start.gap-1
          = link_to 'Show', item, class: 'btn btn-primary'
          = button_to 'Delete', item, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger'
    div.digg_pagination
      div.page_info
        = page_entries_info @rss_items
      = will_paginate @rss_items, :container => false
  .col-md-3
    .form-group
      = form_tag rss_items_path, method: :get, class: 'form-inline' do
        .form-group
          = label_tag :source, 'Filter by Source:', class: 'sr-only'
          = text_field_tag :source, params[:source], class: 'form-control', placeholder: 'Source'

        .form-group
          = label_tag :title, 'Filter by Title:', class: 'sr-only'
          = text_field_tag :title, params[:title], class: 'form-control', placeholder: 'Title'

        .form-group
          = label_tag :publish_date, 'Filter by Publish Date:', class: 'sr-only'
          = date_field_tag :publish_date, params[:publish_date], class: 'form-control', placeholder: 'Publish Date'

        = submit_tag 'Filter', class: 'btn btn-primary'
        = link_to 'Reset', reset_filters_rss_items_path, class: 'btn btn-secondary ml-2'

app/views/rss_items/show.html.slim
div.container
  p style="color: green" = notice

  == render @rss_item

  div.row
    div.col-md-2
      = link_to "Back to archive", rss_items_path, class: "btn btn-primary"

    div.col-md-2
      = button_to "Destroy", @rss_item, method: :delete, class: "btn btn-danger"